export const universityImageCatalog = [
  { slug: "tsinghua", names: ["清华大学", "清华"] },
  { slug: "peking", names: ["北京大学", "北大"] },
  { slug: "fudan", names: ["复旦大学", "复旦"] },
  { slug: "whu", names: ["武汉大学", "武大"] },
  { slug: "xmu", names: ["厦门大学", "厦大"] },
  { slug: "sysu", names: ["中山大学", "中大"] },
  { slug: "scut", names: ["华南理工大学", "华南理工", "华工"] },
  { slug: "jnu", names: ["暨南大学", "暨大"] },
  { slug: "scnu", names: ["华南师范大学", "华南师大", "华师"] },
  { slug: "szu", names: ["深圳大学", "深大"] },
  { slug: "sustech", names: ["南方科技大学", "南科大"] },
  { slug: "gdut", names: ["广东工业大学", "广工"] },
  { slug: "lzu", names: ["兰州大学"] },
  { slug: "njnu", names: ["南京师范大学"] },
  { slug: "cpu", names: ["中国药科大学", "中国药科大学(中外合作办学)"] },
  { slug: "suda", names: ["苏州大学"] },
  { slug: "jlu", names: ["吉林大学"] },
  { slug: "zju", names: ["浙江大学", "浙大"] },
  { slug: "scau", names: ["华南农业大学", "华农"] },
  { slug: "gzhu", names: ["广州大学", "广大"] },
  { slug: "gdufs", names: ["广东外语外贸大学", "广外"] },
  { slug: "sgu", names: ["韶关学院"] },
  { slug: "hzu", names: ["惠州学院"] },
  { slug: "gpnu", names: ["广东技术师范大学"] },
  { slug: "gdou", names: ["广东海洋大学"] },
  { slug: "jyu", names: ["嘉应学院"] },
  { slug: "lingnan-normal", names: ["岭南师范学院"] },
  { slug: "zqu", names: ["肇庆学院"] },
  { slug: "hsnc", names: ["韩山师范学院"] },
  { slug: "neusoft-gd", names: ["广东东软学院"] },
  { slug: "baiyun", names: ["广东白云学院"] },
  { slug: "gzasc", names: ["广州应用科技学院"] },
  { slug: "gnnu", names: ["赣南师范大学"] },
  { slug: "foshan", names: ["佛山大学"] },
  { slug: "gzgs", names: ["广州工商学院"] },
  { slug: "jxnu", names: ["江西师范大学"] },
  { slug: "gdei", names: ["广东第二师范学院"] },
  { slug: "sdfmu", names: ["山东第一医科大学"] },
  { slug: "hainnu", names: ["海南师范大学"] },
  { slug: "hunnu", names: ["湖南师范大学"] },
  { slug: "gzyzy", names: ["广州中医药大学"] },
  { slug: "gdufe", names: ["广东财经大学"] },
  { slug: "tibetu", names: ["西藏大学"] },
  { slug: "bjfu", names: ["北京林业大学"] },
  { slug: "ycu", names: ["宜春学院"] },
  { slug: "gdpu", names: ["广东药科大学"] },
  { slug: "snnu", names: ["陕西师范大学"] },
  { slug: "gduf", names: ["广东金融学院"] },
  { slug: "gdup", names: ["广东石油化工学院"] },
  { slug: "gzrj", names: ["广州软件学院"] }
];
